


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import 'bootstrap/dist/css/bootstrap.min.css';
import app1 from "../styles/app1.module.css";

import Header from '../component/app.header';
import Container from 'react-bootstrap/Container'

import Footer from "@/component/app.footer";
import Modal1 from "@/modals/modal1";
import { ToastContainer, toast } from 'react-toastify';
import type { Metadata } from 'next'


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: 'Homepage',
  description: 'this is the homepage',
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Container>

          {children}

        </Container>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
